[package]
name = "doctor-service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.1"
axum-macros="0.3.0"
tokio = "1"
tracing-subscriber = "0.3"
tracing = "0.1"
mongodb = "2.3.1"
reqwest = { version = "0.11", features = ["json"] }
serde = "1"
anyhow = "1.0"