version: '3'

services:
  mongo:
    image: mongo
    restart: unless-stopped 
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=pielegniarki
      - MONGO_INITDB_ROOT_USERNAME=padmin
      - MONGO_INITDB_ROOT_PASSWORD=zaq1
    volumes:
      - ./data:/data/db:rw

  mongo-express:
    image: mongo-express
    restart: unless-stopped 
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=padmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=zaq1
      - ME_CONFIG_MONGODB_URL=mongodb://padmin:zaq1@mongo:27017/admin